### ISSUE TITLE
Milestone 1 Issues

### ISSUE THREAD

**Issue by aimirza** [UBC-MDS/DSCI_522-ellognea-smwatts-student-performance#32]
**You may close this issue when all issues are resolved and checked.** 

**Mechanics**
- [x] Thank you for describing what each script does in your main README.md file. Please also explain how to run your data analysis (which order scripts are run in, what expected inputs and outputs are). Your explanation could include a flow chart/dependecy diagram. 

**Reasoning**
- [x] You cannot accept the alternative hypothesis, you can only reject or fail to reject the null hypothesis. Unless you are using Bayesian statistics. 

**Visualization**
- [x] More descriptive Figure and table captions. Captions should stand alone. Meaning, the reader should understand the figure by examining the graph and caption alone, and not refer back to the text. For example: "Figure 1. Mean pregnancy length for first babies pregnancy and for other (non-first baby) pregnancy length. Error bars represent 95% confidence intervals generated by boostrapping.)"

**Quality -- Readability and Documentation**
- [x] Use more meaningful self-documentation. For example, describe how the script clean_student_perf_data.R cleans the data in the self-documentation. 
- [x] Use more meaningful comments. 
- [x] Line spacings are not always consistent. 
- [x] Comments in the script analysis_t-test_estimates.R are too long. Split them into multiple lines. 

**Quality -- Robustness and Maintainability**
- [x] Should have a unit test in each script (because we did not clearly mention this in the instructions, we did not deduct points for not having a unit test)

**Grammar and Spelling**
- [x] Misspelled Distribution and alpha. 
- [x] Portuguese should be capitalized.

**Comment by smwatts** [comment]
Re: Quality -- Robustness and Maintainability

We didn't learn how to make unit tests in class yet, are there resources for this?

**Comment by aimirza** [comment]
You had to develop unit tests in 511 for a function that looks up a string in all environments.

**Comment by aimirza** [comment]
The simplest test is to ensure that a dataframe is provided where the columns are variables for example. If you have to use statistics to generate your plot you can use a unit test similar to this example: https://stackoverflow.com/questions/27948126/how-can-i-write-unit-tests-against-code-that-uses-matplotlib

**Comment by ellognea** [comment]
I do not understand the Mechanics feedback - "Please also explain how to run your data analysis (which order scripts are run in, what expected inputs and outputs are)" 

The readme says : "  The data analysis is carried out in 4 scripts saved in the ./src/folder and ran in the following order" 1 ,2,3,4 with description.

Could you please explain - Was the flow chart necessary ?

**Comment by smwatts** [comment]
Addressed all feedback except unit tests & more descriptive comments in https://github.com/UBC-MDS/DSCI_522-ellognea-smwatts-student-performance/pull/33

**Comment by ellognea** [comment]
Re: Quality -- Readability and Documentation

"Use more meaningful comments"  : could you please give an example ?

**Comment by aimirza** [comment]
> Re: Quality -- Readability and Documentation
> 
> "Use more meaningful comments" : could you please give an example ?

Example: In `explore_student_perf.R` right above the code that starts with `violin `say #Create violin plit. For every block of code you should have a comment.

**Comment by aimirza** [comment]
> I do not understand the Mechanics feedback - "Please also explain how to run your data analysis (which order scripts are run in, what expected inputs and outputs are)"
> 
> The readme says : " The data analysis is carried out in 4 scripts saved in the ./src/folder and ran in the following order" 1 ,2,3,4 with description.
> 
> Could you please explain - Was the flow chart necessary ?

Flow chart is not necessary but helpful. What you have now is good. But explain how to run the Makefile (e.g., copy repo, go to root, run these codes, etc) in your main README.md of your projects repo.
